### ISSUE TITLE
有没有遇到过网络连接问题？现在elife通过requests访问不了

### ISSUE THREAD

**Issue by charon181** [MinhZou/FudanCourtReservation#7]
运行脚本的时候报了SSLError
```
Traceback (most recent call last):
  File "D:\anaconda3\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\anaconda3\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\me\Desktop\FudanCourtReservation-main\FudanCourtReservation-main\scripts\client.py", line 552, in single_job
    self.get_status()
  File "c:\Users\me\Desktop\FudanCourtReservation-main\FudanCourtReservation-main\scripts\client.py", line 434, in get_status
    resource_resp = requests.get(status_url, headers=headers)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='elife.fudan.edu.cn', port=443): Max retries exceeded with url: /public/userbox/index.htm?userConfirm=&orderstateselect= (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1006)')))
```
具体出错的那行是函数get_status里的这一行
```python
resource_resp = requests.get(status_url, headers=headers)
```
其中status_url是’https://elife.fudan.edu.cn/public/userbox/index.htm?userConfirm=&orderstateselect=‘

怀疑自己网络连接有问题，于是另开了一个文件去requests服务器。发现百度，甚至ehall都能成功访问
```python
import requests
response = requests.get('https://ehall.fudan.edu.cn')
print(response.status_code)
```
```
200
```
但是偏偏就elife不行
```python
response = requests.get('https://elife.fudan.edu.cn')
print(response.status_code)
```
```
urllib3.exceptions.SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\anaconda3\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='elife.fudan.edu.cn', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
urllib3.exceptions.SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\anaconda3\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='elife.fudan.edu.cn', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\me\Desktop\FudanCourtReservation-main\try_re.py", line 2, in <module>       
    r = requests.get('https://elife.fudan.edu.cn')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='elife.fudan.edu.cn', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1006)')))
```
请问作者有遇到过这种情况吗？包括使用curl也会报一个unsafe legacy renegotiation disabled。是不是最近服务器不让访问了？

**Comment by MinhZou** [comment]
很有可能是使用的python版本和selenium版本的问题，其他可能性可以参考这个closed的issue #1

**Comment by charon181** [comment]
感谢回复，

requests应该用不到selenium，所以可能不是这个版本的问题。issue https://github.com/MinhZou/FudanCourtReservation/issues/1 里面的情况我都看了，和issue 1的提问者一样，排除了这四种可能还是不能直接requests。使用你前几日更新的版本后，可以在Linux上可以通过下面的代码成功访问了，但是还是不能直接requests

```
import urllib3
import ssl
import requests

class CustomHttpAdapter (requests.adapters.HTTPAdapter):
    def __init__(self, ssl_context=None, **kwargs):
        self.ssl_context = ssl_context
        super().__init__(**kwargs)

    def init_poolmanager(self, connections, maxsize, block=False):
        self.poolmanager = urllib3.poolmanager.PoolManager(
            num_pools=connections, maxsize=maxsize,
            block=block, ssl_context=self.ssl_context)
        
def get_legacy_session():
    ctx = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
    ctx.options |= 0x4
    session = requests.session()
    session.mount('https://', CustomHttpAdapter(ctx))
    return session

status_url = 'https://elife.fudan.edu.cn/public/userbox/index.htm?userConfirm=&orderstateselect='
s = get_legacy_session()
s.get(status_url)
```

另外请教一下作者有没有在linux服务器上测试过该项目？直接挂内网服务器的话，网络可能会好一些。但我还没有跑通linux上的chorme driver

**Comment by MinhZou** [comment]
刚刚测试了下，还是可以正常运行的。 9月1号更新的解决的就是这个问题，当时也花了很多时间，核心是python版本的问题或者是request库，python版本大于可能是3.10+，也可能是3.9还是3.8，从某个版本开始，默认安装的requests库不支持一些低版本的不安全的访问。

**Comment by MinhZou** [comment]
这个代码的前置版本以前在带桌面的Ubuntu系统上能成功运行，也是部分基于selenium，改完之后的版本应该可以运行的，可能需要重点考虑的问题是linux系统的chorme浏览器版本和webdriver的对应。
