### ISSUE TITLE
get_cookie_by_selenium时出错

### ISSUE THREAD

**Issue by charon181** [MinhZou/FudanCourtReservation#8]
获取cookie时出错
```
[2024-09-08 22:50:10,593 - root - INFO - 1955109 - 140407936620352] *********************************Settings******************************
[2024-09-08 22:50:10,594 - root - INFO - 1955109 - 140407936620352] 预定人: ***
[2024-09-08 22:50:10,594 - root - INFO - 1955109 - 140407936620352] 手机号: ***
[2024-09-08 22:50:10,594 - root - INFO - 1955109 - 140407936620352] 今天的日期: 2024-09-08
[2024-09-08 22:50:10,594 - root - INFO - 1955109 - 140407936620352] 预定的日期: 2024-09-10
[2024-09-08 22:50:10,594 - root - INFO - 1955109 - 140407936620352] 预定的场地：江湾体育馆排球场1号
[2024-09-08 22:50:10,594 - root - INFO - 1955109 - 140407936620352] 预定的时间段：['12:00']
[2024-09-08 22:50:10,595 - root - INFO - 1955109 - 140407936620352] 已预约的时间段：{}
[2024-09-08 22:50:10,595 - root - INFO - 1955109 - 140407936620352] ***********************************************************************
[2024-09-08 22:50:16,725 - root - INFO - 1955109 - 140407936620352] Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=128.0.6613.119)
Stacktrace:
#0 0x55db1a6da86a <unknown>
#1 0x55db1a3a8e50 <unknown>
#2 0x55db1a38f8a8 <unknown>
#3 0x55db1a38f783 <unknown>
#4 0x55db1a3ab142 <unknown>
#5 0x55db1a43b29f <unknown>
#6 0x55db1a41d233 <unknown>
#7 0x55db1a3eb093 <unknown>
#8 0x55db1a3ec09e <unknown>
#9 0x55db1a6a1acb <unknown>
#10 0x55db1a6a5a81 <unknown>
#11 0x55db1a68d695 <unknown>
#12 0x55db1a6a65f2 <unknown>
#13 0x55db1a67286f <unknown>
#14 0x55db1a6c9668 <unknown>
#15 0x55db1a6c9832 <unknown>
#16 0x55db1a6d965c <unknown>
#17 0x7fc24d3d4609 start_thread

Process Process-4:
Traceback (most recent call last):
  File "/home/jupyter-stu19/FudanCourtReservation-main/scripts/client.py", line 462, in single_job
    self.cookie = self.get_cookie_by_selenium()
  File "/home/jupyter-stu19/FudanCourtReservation-main/scripts/client.py", line 155, in get_cookie_by_selenium
    browser.find_element(By.ID,"username").send_keys("{}".format(self.username))
  File "/home/jupyter-stu19/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 748, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/home/jupyter-stu19/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/jupyter-stu19/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=128.0.6613.119)
Stacktrace:
#0 0x55db1a6da86a <unknown>
#1 0x55db1a3a8e50 <unknown>
#2 0x55db1a38f8a8 <unknown>
#3 0x55db1a38f783 <unknown>
#4 0x55db1a3ab142 <unknown>
#5 0x55db1a43b29f <unknown>
#6 0x55db1a41d233 <unknown>
#7 0x55db1a3eb093 <unknown>
#8 0x55db1a3ec09e <unknown>
#9 0x55db1a6a1acb <unknown>
#10 0x55db1a6a5a81 <unknown>
#11 0x55db1a68d695 <unknown>
#12 0x55db1a6a65f2 <unknown>
#13 0x55db1a67286f <unknown>
#14 0x55db1a6c9668 <unknown>
#15 0x55db1a6c9832 <unknown>
#16 0x55db1a6d965c <unknown>
#17 0x7fc24d3d4609 start_thread
```
具体是在browser.find_element这一行出错
```
browser.get("https://uis.fudan.edu.cn/authserver/login?service=https%3A%2F%2Felife.fudan.edu.cn%2Flogin2.action")
browser.find_element(By.ID,"username").send_keys("{}".format(self.username))
```
然而错误本身应该不在find_element上，因为下面的代码也会报一样的错
```
browser.get("https://uis.fudan.edu.cn/authserver/login?service=https%3A%2F%2Felife.fudan.edu.cn%2Flogin2.action")
print(browser.title)
```
请问作者有遇到过类似的问题吗？测试平台为Linux，chrome和chromedriver为同一版本

测试了其他网址，elife.fudan.edu.cn同样报错，但ehall.fudan.edu.cn和baidu.com不会报错

**Comment by charon181** [comment]
该问题已解决，原因是服务器上缺少字体来渲染网页（chrome是绕过sudo自己安装的）

**Comment by charon181** [comment]
有时候这个错误会短暂地消失，但很多时候依然存在

**Comment by MinhZou** [comment]
没有遇到过，可能是页面没有加载出来，等待加载一段时间或者可以直接在浏览器中手动输入和访问上面的链接，看可能出现什么异常情况。

**Comment by charon181** [comment]
感谢MinhZou的回复。可能确实是页面没加载出来。虽然我什么都没做，但是现在这个错误不再出现了。
